FROM alpine

ARG TARGETARCH

# Dependencies
RUN apk add --no-cache bash tini

# Application
COPY ./dist/${TARGETARCH}/ttya /usr/bin/ttya

EXPOSE 7681
WORKDIR /root

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["ttya", "-W", "bash"]
